TOKEN = "your token should be here"

STICKER_ID = [
    "CAACAgIAAxkBAAIHi199vb4_E6RaMEAXDRJlZwXwKsR8AAIQAwACtXHaBg7pgf4mdlGzGwQ",
    "CAACAgIAAxkBAAIHnl99wniTImw7gr0x935PXPJKb_37AAIBAQACVp29CiK-nw64wuY0GwQ",
    "CAACAgIAAxkBAAIHn199wn89zeXewCsn0sildGyNr9DLAAIKAQAClp-MDiG-gmZwLFc8GwQ",
    "CAACAgIAAxkBAAIHoF99wopVq0Gbes-iSIhYIvKfFGLiAAIMAQAClp-MDl84Fd3ceGu2GwQ",
    "CAACAgIAAxkBAAIHoV99wpXfDWIHYK6nyW6yIITljA4RAAIEAQACVp29Ct4E0XpmZvdsGwQ",
    "CAACAgIAAxkBAAIHol99wp4bxCZ1J31pKpiEE8RGfQZCAAInAwACtXHaBg_03s-gxd3sGwQ",
    "CAACAgIAAxkBAAIHo199wqi09xC34f796Bl0aQABmz3VVwACDQMAArVx2gZFgpxbL_Mw5xsE",
    "CAACAgIAAxkBAAIIhV9_diOkYLegVhix3BoFyRURPyp2AAIgAANZu_wlhYqWmghNyX0bBA",
    "CAACAgIAAxkBAAIIiF9_d2Xt0xzYyqxgesbv7hzuxSTDAAL1AwACRxVoCYDkI4apaTHtGwQ",
    "CAACAgIAAxkBAAIIiV9_d4iDBwENpDtp1OiHRrPgCTyPAAJOAQACIjeOBICDUmQWTPmZGwQ",
    "CAACAgIAAxkBAAIIil9_d5M1SE27QLTrkDzmE1Qs44G0AAJJAQACIjeOBElL_7UZ91JxGwQ",
    "CAACAgIAAxkBAAIIi19_d7C6q_FvQJcEds4PcNWyvxCeAAJQAANSiZEj0YLxZBXhJNgbBA",
    "CAACAgIAAxkBAAIIjF9_d7RRjij8uZIBHN3ZpJkUywKMAAI6AANSiZEjyxUs5tYqNLobBA"
    ]   

GIF_ID = [
    "CgACAgIAAxkBAAIjPF_rJJ127z043nuRmgSirs-pRy6eAAJXCwACaI9ZS5VyNqaH8DbyHgQ",
    "CgACAgIAAxkBAAIjPV_rJJiArWYX0Uj9zy0BgLftzL6DAAJYCwACaI9ZS6D0te94lzHaHgQ",
    "CgACAgIAAxkBAAIjPl_rJJO_9BpPhhffJ9trpak8B2RKAAJZCwACaI9ZSzt-l-OsBfp0HgQ",
    "CgACAgIAAxkBAAIjP1_rJKanu7i2Y_ZNgKfvs1HPaykKAAJaCwACaI9ZS1nrCyWh8Q-kHgQ"
]
